In [0]:
import pandas
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [0]:
iris_path = "/content/drive/My Drive/Semester 8/DSci/Lab/Lab4/Iris/iris.data"
data_training_path = "/content/drive/My Drive/Semester 8/DSci/Lab/Lab4/Occupency_Detection/datatraining.txt"
data_test1_path = "/content/drive/My Drive/Semester 8/DSci/Lab/Lab4/Occupency_Detection/datatest.txt"
data_test2_path = "/content/drive/My Drive/Semester 8/DSci/Lab/Lab4/Occupency_Detection/datatest2.txt"

In [0]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pandas.read_csv(iris_path, names=names)

In [0]:
dataset.shape

(150, 5)

In [0]:
dataset.groupby('class').size()

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64

In [0]:
array = dataset.values
X = array[:,0:4]
Y = array[:,4]
t_size = 0.20
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size,
random_state=seed)

# display(Y)
# display(Y_train)
# display(Y_test)

In [0]:
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
predictions = knn.predict(X_test)
print(accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

0.9
[[ 7  0  0]
 [ 0 11  1]
 [ 0  2  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.85      0.92      0.88        12
 Iris-virginica       0.90      0.82      0.86        11

       accuracy                           0.90        30
      macro avg       0.92      0.91      0.91        30
   weighted avg       0.90      0.90      0.90        30



In [0]:
for i in range(1,10):
  knn = KNeighborsClassifier(i)
  knn.fit(X_train, Y_train)
  predictions = knn.predict(X_test)
  print("Accuracy= ",accuracy_score(Y_test, predictions))


Accuracy=  0.9
Accuracy=  0.9333333333333333
Accuracy=  0.9
Accuracy=  0.9333333333333333
Accuracy=  0.9
Accuracy=  0.8666666666666667
Accuracy=  0.8666666666666667
Accuracy=  0.9
Accuracy=  0.9


In [0]:
for i in range(1,10):
  X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size,
random_state=i)
  knn = KNeighborsClassifier(i)
  knn.fit(X_train, Y_train)
  predictions = knn.predict(X_test)
  print("Seed= {0},  Accuracy= {1} ".format(i,accuracy_score(Y_test, predictions)))


Seed= 1,  Accuracy= 1.0 
Seed= 2,  Accuracy= 1.0 
Seed= 3,  Accuracy= 0.9666666666666667 
Seed= 4,  Accuracy= 0.9666666666666667 
Seed= 5,  Accuracy= 0.9333333333333333 
Seed= 6,  Accuracy= 1.0 
Seed= 7,  Accuracy= 0.8666666666666667 
Seed= 8,  Accuracy= 0.9666666666666667 
Seed= 9,  Accuracy= 1.0 


# **Question #2**

In [0]:
# Repeat (I) using Occupancy Detection dataset. Ignore Date Attribute. Off course, steps (d)
# and (g) are not applicable since training / test data is given.
names= ["Date","Temperature",	"Humidity",	"Light",	"CO2",	"HumidityRatio",	"Occupancy"]
dataset = pandas.read_csv(data_training_path, names=names, header=0)
dataset.drop(dataset.columns[0], axis=1, inplace=True)
# display(dataset)

In [0]:
names= ["Date","Temperature",	"Humidity",	"Light",	"CO2",	"HumidityRatio",	"Occupancy"]

dataset_test1 = pandas.read_csv(data_test1_path, names=names, header=0)
dataset_test2 = pandas.read_csv(data_test2_path, names=names, header=0)

dataset_test1.drop(dataset_test1.columns[0], axis=1, inplace=True)
dataset_test2.drop(dataset_test2.columns[0], axis=1, inplace=True)

# display(dataset_test1)
# display(dataset_test2)

In [0]:
display(dataset_test1.shape)
display(dataset_test2.shape)

(2665, 6)

(9752, 6)

In [0]:
array = dataset.values
X_train = array[:,0:5]
Y_train = array[:,5]
# display(X_train)
# display(Y_train)


array_test1 = dataset_test1.values
X_test1 = array_test1[:,0:5]
Y_test1 = array_test1[:,5]

# display(X_test1)
# display(Y_test1)


array_test2 = dataset_test2.values
X_test2 = array_test2[:,0:5]
Y_test2 = array_test2[:,5]


# display(X_test2)
# display(Y_test2)

In [0]:
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
predictions = knn.predict(X_test1)
print(accuracy_score(Y_test1, predictions))
print(confusion_matrix(Y_test1, predictions))
print(classification_report(Y_test1, predictions))


#Accuracy
print("************************* Part 'F' Accuracy *************************\n ")
for i in range(1,10):
  knn = KNeighborsClassifier(i)
  knn.fit(X_train, Y_train)
  predictions = knn.predict(X_test1)
  print("Accuracy Test1 = ",accuracy_score(Y_test1, predictions))

0.9425891181988743
[[1645   48]
 [ 105  867]]
              precision    recall  f1-score   support

         0.0       0.94      0.97      0.96      1693
         1.0       0.95      0.89      0.92       972

    accuracy                           0.94      2665
   macro avg       0.94      0.93      0.94      2665
weighted avg       0.94      0.94      0.94      2665

************************* Part 'F' Accuracy *************************
 
Accuracy Test1 =  0.9365853658536586
Accuracy Test1 =  0.9230769230769231
Accuracy Test1 =  0.9350844277673546
Accuracy Test1 =  0.9275797373358349
Accuracy Test1 =  0.9425891181988743
Accuracy Test1 =  0.9324577861163227
Accuracy Test1 =  0.9609756097560975
Accuracy Test1 =  0.9549718574108818
Accuracy Test1 =  0.9617260787992495


In [0]:
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
predictions = knn.predict(X_test2)
print(accuracy_score(Y_test2, predictions))
print(confusion_matrix(Y_test2, predictions))
print(classification_report(Y_test2, predictions))


#Accuracy
print("************************* Part 'F' Accuracy *************************\n ")
for i in range(1,10):
  knn = KNeighborsClassifier(i)
  knn.fit(X_train, Y_train)
  predictions = knn.predict(X_test2)
  print("Accuracy Test2 = ",accuracy_score(Y_test2, predictions))

0.9621616078753076
[[7385  318]
 [  51 1998]]
              precision    recall  f1-score   support

         0.0       0.99      0.96      0.98      7703
         1.0       0.86      0.98      0.92      2049

    accuracy                           0.96      9752
   macro avg       0.93      0.97      0.95      9752
weighted avg       0.97      0.96      0.96      9752

************************* Part 'F' Accuracy *************************
 
Accuracy Test2 =  0.9502666119770303
Accuracy Test2 =  0.9525225594749795
Accuracy Test2 =  0.9579573420836751
Accuracy Test2 =  0.9539581624282198
Accuracy Test2 =  0.9621616078753076
Accuracy Test2 =  0.9628794093519278
Accuracy Test2 =  0.9649302707136997
Accuracy Test2 =  0.9658531583264971
Accuracy Test2 =  0.9656480721903199


## **Question # 3**

In [0]:
# dataset
# dataset_test1
# dataset_test2

names= ["Date","Temperature",	"Humidity",	"Light",	"CO2",	"HumidityRatio",	"Occupancy"]
dataset = pandas.read_csv(data_training_path, names=names, header=0)
dataset.drop(dataset.columns[0], axis=1, inplace=True)
# display(dataset)

In [0]:
names= ["Date","Temperature",	"Humidity",	"Light",	"CO2",	"HumidityRatio",	"Occupancy"]

dataset_test1 = pandas.read_csv(data_test1_path, names=names, header=0)
dataset_test2 = pandas.read_csv(data_test2_path, names=names, header=0)

dataset_test1.drop(dataset_test1.columns[0], axis=1, inplace=True)
dataset_test2.drop(dataset_test2.columns[0], axis=1, inplace=True)

# display(dataset_test1)
# display(dataset_test2)

In [0]:
array = dataset.values
X_train = array[:,0:5]
Y_train = array[:,5]
# display(X_train)
# display(Y_train)


array_test1 = dataset_test1.values
X_test1 = array_test1[:,0:5]
Y_test1 = array_test1[:,5]

# display(X_test1)
# display(Y_test1)


array_test2 = dataset_test2.values
X_test2 = array_test2[:,0:5]
Y_test2 = array_test2[:,5]


# display(X_test2)
# display(Y_test2)

print(X_train[219],"\n",X_test1[219])
print(Y_train[219],"\n",Y_test1[219])

[2.15000000e+01 2.58400000e+01 0.00000000e+00 4.90000000e+02
 4.09552268e-03] 
 [2.23900000e+01 2.47170833e+01 4.19000000e+02 7.72925000e+02
 4.13646442e-03]
0.0 
 1.0


In [0]:
np.sum(np.square(X_train[219] - X_test1[219]) / (X_train[219] + X_test1[219]))

482.42486445101076

In [0]:
import numpy as np
from collections import Counter


def Chi_Square(training_data , test_sample, training_labels):
  # print("\nHello Inside ChiSquare", end="")
  distance = {}    # distance of test sample with each training sample
  for train_sample, train_label, index in zip(training_data, training_labels, range(len(training_data))):
    d = (np.sum(np.square(train_sample - test_sample) / (train_sample + test_sample)) , index )
    distance[d] = train_label
  
  return distance  # returns list of chi square distance of single test sample


#  X_train, X_test1, X_test2 (data),  Y_train, Y_test1, Y_test2 (labels)  

def predict( k ,Chi_Sq_Distance_Test_Sample,  Actual_test_sample_label):
  distances = list(Chi_Sq_Distance_Test_Sample.keys())
  distance_sorted = sorted(distances)
  
  # print("\nHello Inside Predict")
  
  K_minimum_Distance = distance_sorted[:k]

  # indexes = [distances.index(i) for i in K_minimum_Distance ]   # Actual Test Sample Location
  # distance.index( np.min(distance) ) ,  np.min(distance)
  
  predicted_labels = [Chi_Sq_Distance_Test_Sample[i] for i in K_minimum_Distance] 
  # print(predicted_labels, end=" ")
  
  if len(predicted_labels)>1:
    predicted_label=Counter(predicted_labels)
    if predicted_label[1.] > predicted_label[0.]:
      predicted_label = 1.
    elif predicted_label[1.] < predicted_label[0.]:
      predicted_label = 0.
    else:
      predicted_label = predicted_labels[np.random.randint(len(predicted_labels))]

  else:
    predicted_label = predicted_labels[0]

  correctly_classified = True if Actual_test_sample_label == predicted_label else False

  return predicted_label, correctly_classified



for k in range(1,10):
  Accuracy=0
  for test_sample,test_label in zip(X_test1,Y_test1):
  
    Distance = Chi_Square(X_train ,test_sample, Y_train)  #Dictionary with Training_Data Label
    Predicted_Label_for_test_sample, Correctly_Classified = predict(k, Distance, test_label)
    if Correctly_Classified == True:
      Accuracy+=1 
  print("Accuracy for K=", k, "is : ", Accuracy/X_test1.shape[0])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


Accuracy for K= 1 is :  0.9212007504690432
Accuracy for K= 2 is :  0.924202626641651
